site_name: CMU 11781/02741 Generative AI for Biomedicine 2026 Fall Assignments
nav:
  - Home: index.md
  - Grading rubric: grading_rubric.md
site_url: https://genaibiomed.github.io/GenAIBioMedAssignment3/
theme:
  name: material
extra_css:
  - stylesheets/figures.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
